# Generated by Django 5.2.14 on 2026-05-23 13:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlateEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('entry', 'Entry'), ('exit', 'Exit'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('image', models.ImageField(upload_to='plate-events/%Y/%m/%d/')),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('plate_text', models.CharField(blank=True, max_length=16)),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error')], default='pending', max_length=32)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('pipeline_metadata', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='cameras.camera')),
            ],
            options={
                'ordering': ['-captured_at', '-id'],
                'indexes': [models.Index(fields=['plate_text'], name='plates_plat_plate_t_98cad8_idx'), models.Index(fields=['status', 'captured_at'], name='plates_plat_status_674ad6_idx')],
            },
        ),
    ]
