# Generated by Django 5.2.14 on 2026-05-23 14:41

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_gateway_camera_camera_key_camera_connection_mode_and_more'),
        ('plates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlateRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=16)),
                ('normalized_plate', models.CharField(max_length=16)),
                ('list_type', models.CharField(choices=[('whitelist', 'Whitelist'), ('blacklist', 'Blacklist'), ('unknown', 'Unknown')], max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('ignored', 'Ignored')], default='active', max_length=32)),
                ('owner_name', models.CharField(blank=True, max_length=160)),
                ('owner_document', models.CharField(blank=True, max_length=80)),
                ('vehicle_model', models.CharField(blank=True, max_length=120)),
                ('vehicle_color', models.CharField(blank=True, max_length=80)),
                ('vehicle_type', models.CharField(blank=True, max_length=80)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('block_reason', models.CharField(blank=True, max_length=255)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_plate_registries', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_plate_registries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['normalized_plate', 'list_type'],
            },
        ),
        migrations.CreateModel(
            name='AccessEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('plate_text', models.CharField(blank=True, max_length=16)),
                ('normalized_plate', models.CharField(blank=True, max_length=16)),
                ('list_type_result', models.CharField(blank=True, max_length=32)),
                ('decision', models.CharField(choices=[('allowed', 'Allowed'), ('blocked', 'Blocked'), ('unknown', 'Unknown'), ('manual_review', 'Manual review'), ('error', 'Error')], default='unknown', max_length=32)),
                ('decision_reason', models.TextField(blank=True)),
                ('movement_type', models.CharField(choices=[('entry', 'Entry'), ('exit', 'Exit'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='access-events/%Y/%m/%d/')),
                ('crop_image', models.ImageField(blank=True, upload_to='access-events/crops/%Y/%m/%d/')),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('processed', 'Processed'), ('error', 'Error')], default='received', max_length=32)),
                ('error_message', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=120)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='access_events', to='cameras.camera')),
                ('gateway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_events', to='cameras.gateway')),
                ('plate_event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_event', to='plates.plateevent')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_access_events', to=settings.AUTH_USER_MODEL)),
                ('plate_registry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_events', to='plates.plateregistry')),
            ],
            options={
                'ordering': ['-captured_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VehiclePresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalized_plate', models.CharField(max_length=16, unique=True)),
                ('current_status', models.CharField(choices=[('inside', 'Inside'), ('outside', 'Outside'), ('inconsistent', 'Inconsistent'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('entered_at', models.DateTimeField(blank=True, null=True)),
                ('exited_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('inconsistency_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_entry_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='plates.accessevent')),
                ('last_exit_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='plates.accessevent')),
                ('plate_registry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presence_records', to='plates.plateregistry')),
            ],
            options={
                'ordering': ['normalized_plate'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('blacklist_detected', 'Blacklist detected'), ('unknown_plate_detected', 'Unknown plate detected'), ('manual_review_required', 'Manual review required'), ('gateway_offline', 'Gateway offline'), ('camera_offline', 'Camera offline'), ('duplicate_entry', 'Duplicate entry'), ('exit_without_entry', 'Exit without entry')], max_length=64)),
                ('plate', models.CharField(blank=True, max_length=16)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=32)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=32)),
                ('message', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='plates.accessevent')),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='cameras.camera')),
                ('gateway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='cameras.gateway')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['alert_type', 'status', 'created_at'], name='plates_aler_alert_t_f3bb9c_idx'), models.Index(fields=['plate', 'status'], name='plates_aler_plate_036285_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='plateregistry',
            index=models.Index(fields=['normalized_plate', 'list_type', 'status'], name='plates_plat_normali_1dd4dc_idx'),
        ),
        migrations.AddConstraint(
            model_name='plateregistry',
            constraint=models.UniqueConstraint(fields=('normalized_plate', 'list_type'), name='unique_plate_per_registry_type'),
        ),
        migrations.AddIndex(
            model_name='accessevent',
            index=models.Index(fields=['normalized_plate', 'captured_at'], name='plates_acce_normali_c7efaa_idx'),
        ),
        migrations.AddIndex(
            model_name='accessevent',
            index=models.Index(fields=['camera', 'captured_at'], name='plates_acce_camera__97f708_idx'),
        ),
        migrations.AddIndex(
            model_name='accessevent',
            index=models.Index(fields=['decision', 'captured_at'], name='plates_acce_decisio_7c170d_idx'),
        ),
        migrations.AddIndex(
            model_name='accessevent',
            index=models.Index(fields=['movement_type', 'captured_at'], name='plates_acce_movemen_81ec11_idx'),
        ),
        migrations.AddConstraint(
            model_name='accessevent',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('camera', 'idempotency_key'), name='unique_camera_idempotency_key'),
        ),
    ]
