# Generated by Django 5.2.14 on 2026-05-23 14:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_gateway_camera_camera_key_camera_connection_mode_and_more'),
        ('plates', '0002_plateregistry_accessevent_vehiclepresence_alert_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='accessevent',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('gateway', 'idempotency_key'), name='unique_gateway_idempotency_key'),
        ),
    ]
