# Generated by Django 5.2.14 on 2026-05-23 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plates', '0003_accessevent_unique_gateway_idempotency_key'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='plateregistry',
            name='unique_plate_per_registry_type',
        ),
        migrations.AddField(
            model_name='accessevent',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='access_events', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='alert',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='plateevent',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plate_events', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='plateregistry',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plate_registries', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='vehiclepresence',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_presence_records', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='vehiclepresence',
            name='normalized_plate',
            field=models.CharField(max_length=16),
        ),
        migrations.AddConstraint(
            model_name='plateregistry',
            constraint=models.UniqueConstraint(fields=('tenant', 'normalized_plate', 'list_type'), name='unique_plate_per_registry_type'),
        ),
        migrations.AddConstraint(
            model_name='vehiclepresence',
            constraint=models.UniqueConstraint(fields=('tenant', 'normalized_plate'), name='unique_vehicle_presence_per_tenant'),
        ),
    ]
