# Generated by Django 5.2.14 on 2026-05-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeadLetterTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('task_id', models.CharField(blank=True, max_length=255)),
                ('queue', models.CharField(default='dead', max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('exception_class', models.CharField(blank=True, max_length=255)),
                ('exception_message', models.TextField(blank=True)),
                ('traceback', models.TextField(blank=True)),
                ('retries', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reprocessed', 'Reprocessed'), ('ignored', 'Ignored')], default='pending', max_length=32)),
                ('reprocessed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
