# Generated by Django 5.2.14 on 2026-05-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_webhooksubscription_auditlog_webhookdelivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataProcessingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('purpose', models.TextField()),
                ('legal_basis', models.CharField(max_length=255)),
                ('data_categories', models.JSONField(blank=True, default=list)),
                ('retention_days', models.PositiveIntegerField(default=90)),
                ('third_party_sharing', models.TextField(blank=True)),
                ('owner', models.CharField(blank=True, max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DataSubjectRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('access', 'Access'), ('correction', 'Correction'), ('deletion', 'Deletion'), ('objection', 'Objection')], max_length=32)),
                ('requester_name', models.CharField(max_length=160)),
                ('requester_contact', models.CharField(max_length=255)),
                ('plate_text', models.CharField(blank=True, max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='open', max_length=32)),
                ('response_notes', models.TextField(blank=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('notified', 'Notified'), ('closed', 'Closed')], default='open', max_length=32)),
                ('detected_at', models.DateTimeField()),
                ('anpd_due_at', models.DateTimeField(blank=True, null=True)),
                ('anpd_notified_at', models.DateTimeField(blank=True, null=True)),
                ('affected_data', models.JSONField(blank=True, default=list)),
                ('mitigation_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='AIModelArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('yolo', 'YOLO'), ('ocr', 'OCR')], max_length=32)),
                ('version', models.CharField(max_length=120)),
                ('storage_uri', models.CharField(max_length=1000)),
                ('file_sha256', models.CharField(blank=True, max_length=80)),
                ('baseline_metrics', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('promoted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['kind', '-created_at'],
                'indexes': [models.Index(fields=['kind', 'is_active'], name='common_aimo_kind_cbe0a9_idx')],
                'constraints': [models.UniqueConstraint(fields=('kind', 'version'), name='unique_ai_model_version')],
            },
        ),
    ]
