# Generated by Django 5.2.14 on 2026-05-23 14:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_dataprocessingrecord_datasubjectrequest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='entity_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='entity_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='new_value',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='old_value',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='webhooksubscription',
            name='event_type',
            field=models.CharField(choices=[('plate.read', 'Plate read'), ('plate.error', 'Plate error'), ('access.event', 'Access event'), ('task.dead_letter', 'Task dead letter')], max_length=64),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['entity_type', 'entity_id'], name='common_audi_entity__147a18_idx'),
        ),
    ]
