# Generated by Django 5.2.14 on 2026-05-23 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auditlog_entity_id_auditlog_entity_type_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='aimodelartifact',
            name='unique_ai_model_version',
        ),
        migrations.AddField(
            model_name='aimodelartifact',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ai_model_artifacts', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='dataprocessingrecord',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='data_processing_records', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='datasubjectrequest',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='data_subject_requests', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='deadlettertask',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dead_letter_tasks', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='securityincident',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='security_incidents', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='webhookdelivery',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='webhook_deliveries', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='webhooksubscription',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='webhook_subscriptions', to='tenants.tenant'),
        ),
        migrations.AddConstraint(
            model_name='aimodelartifact',
            constraint=models.UniqueConstraint(fields=('tenant', 'kind', 'version'), name='unique_ai_model_version'),
        ),
    ]
