# Generated by Django 5.2.14 on 2026-05-23 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('legal_name', models.CharField(blank=True, max_length=220)),
                ('document', models.CharField(blank=True, max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('document', models.CharField(blank=True, max_length=40)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('timezone', models.CharField(default='America/Sao_Paulo', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='tenants.business')),
            ],
            options={
                'ordering': ['business__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserTenantAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('operator', 'Operator'), ('viewer', 'Viewer')], default='operator', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='tenants.business')),
                ('tenant', models.ForeignKey(blank=True, help_text='Blank means access to all tenants in the business.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username', 'business__name', 'tenant__name'],
                'constraints': [models.UniqueConstraint(fields=('user', 'business', 'tenant'), name='unique_user_business_tenant_access')],
            },
        ),
    ]
