# Generated by Django 5.2.14 on 2026-05-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField(default=554)),
                ('rtsp_path', models.CharField(default='/', max_length=500)),
                ('username', models.CharField(blank=True, max_length=120)),
                ('password_encrypted', models.TextField(blank=True)),
                ('timezone', models.CharField(default='America/Sao_Paulo', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
