# Generated by Django 5.2.14 on 2026-05-23 14:41

import django.db.models.deletion
from django.db import migrations, models

import cameras.models


def populate_camera_keys(apps, schema_editor):
    camera_model = apps.get_model("cameras", "Camera")
    for camera in camera_model.objects.filter(camera_key__isnull=True):
        camera.camera_key = cameras.models._public_key()
        camera.save(update_fields=["camera_key"])


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('gateway_key', models.CharField(default=cameras.models._public_key, max_length=64, unique=True)),
                ('token_hash', models.CharField(blank=True, max_length=128)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('unknown', 'Unknown'), ('online', 'Online'), ('offline', 'Offline')], default='unknown', max_length=32)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=80)),
                ('pending_events', models.PositiveIntegerField(default=0)),
                ('cameras_online', models.PositiveIntegerField(default=0)),
                ('cameras_offline', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='camera',
            name='camera_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='connection_mode',
            field=models.CharField(choices=[('direct_rtsp', 'Direct RTSP'), ('push', 'Push'), ('gateway', 'Gateway')], default='direct_rtsp', max_length=32),
        ),
        migrations.AddField(
            model_name='camera',
            name='direction_default',
            field=models.CharField(choices=[('entry', 'Entry'), ('exit', 'Exit'), ('unknown', 'Unknown')], default='unknown', max_length=32),
        ),
        migrations.AddField(
            model_name='camera',
            name='ingest_token_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='camera',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='camera',
            name='host',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='camera',
            name='gateway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cameras', to='cameras.gateway'),
        ),
        migrations.RunPython(populate_camera_keys, migrations.RunPython.noop),
    ]
