# Generated by Django 5.2.14 on 2026-05-23 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_gateway_camera_camera_key_camera_connection_mode_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cameras', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='gateway',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gateways', to='tenants.tenant'),
        ),
    ]
