# Generated by Django 5.2.14 on 2026-05-29 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0004_camera_rtmp_push_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='lpr_roi',
            field=models.JSONField(blank=True, help_text='Região de interesse para LPR: [x, y, largura, altura] em pixels. Deixe vazio para analisar o frame inteiro.', null=True),
        ),
    ]
